package com.example.finalcompose.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val md_theme_light_primary = Color(0xFF006B5C)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF77F8DF)
val md_theme_light_onPrimaryContainer = Color(0xFF00201B)
val md_theme_light_secondary = Color(0xFF4A635D)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCDE8E0)
val md_theme_light_onSecondaryContainer = Color(0xFF06201B)
val md_theme_light_tertiary = Color(0xFF984800)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDBC8)
val md_theme_light_onTertiaryContainer = Color(0xFF311300)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_outline = Color(0xFF6F7976)
val md_theme_light_background = Color(0xFFFAFDFA)
val md_theme_light_onBackground = Color(0xFF191C1B)
val md_theme_light_surface = Color(0xFFF8FAF7)
val md_theme_light_onSurface = Color(0xFF191C1B)
val md_theme_light_surfaceVariant = Color(0xFFDAE5E1)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4946)
val md_theme_light_inverseSurface = Color(0xFF2D3130)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1EF)
val md_theme_light_inversePrimary = Color(0xFF58DBC3)
val md_theme_light_surfaceTint = Color(0xFF006B5C)
val md_theme_light_outlineVariant = Color(0xFFBEC9C5)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF58DBC3)
val md_theme_dark_onPrimary = Color(0xFF00382F)
val md_theme_dark_primaryContainer = Color(0xFF005045)
val md_theme_dark_onPrimaryContainer = Color(0xFF77F8DF)
val md_theme_dark_secondary = Color(0xFFB1CCC4)
val md_theme_dark_onSecondary = Color(0xFF1C352F)
val md_theme_dark_secondaryContainer = Color(0xFF334B46)
val md_theme_dark_onSecondaryContainer = Color(0xFFCDE8E0)
val md_theme_dark_tertiary = Color(0xFFFFB689)
val md_theme_dark_onTertiary = Color(0xFF512300)
val md_theme_dark_tertiaryContainer = Color(0xFF733500)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDBC8)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_outline = Color(0xFF89938F)
val md_theme_dark_background = Color(0xFF191C1B)
val md_theme_dark_onBackground = Color(0xFFE0E3E1)
val md_theme_dark_surface = Color(0xFF101413)
val md_theme_dark_onSurface = Color(0xFFC4C7C5)
val md_theme_dark_surfaceVariant = Color(0xFF3F4946)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC9C5)
val md_theme_dark_inverseSurface = Color(0xFFE0E3E1)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1B)
val md_theme_dark_inversePrimary = Color(0xFF006B5C)
val md_theme_dark_surfaceTint = Color(0xFF58DBC3)
val md_theme_dark_outlineVariant = Color(0xFF3F4946)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF206A5D)

val center_radial_gradient = Color(0xFF91FB7F)
val middle_radial_gradient = Color(0xFF59D797)
val outer_radial_gradient = Color(0xFF33BFA8)

val fauna_outline = Color(0xFFFF8E3B)
val flora_outline = Color(0xFF33BFA8)

val outline_rank_one = Color(0xFFF5E649)
val outline_rank_two = Color(0xFF6F7976)
val outline_rank_three = Color(0xFF984800)

val user_information = Color(0xFF00382F)